- name: mongodb installation
  hosts: mongodb
  become: yes
  tasks:
    - name: copying mongo.repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: vim /etc/yum.repos.d/mongo.repo

    - name: installing mongodb-org -y
      ansible.builtin.dnf:
        name: mongodb
        state: present

    - name: start and enable mongodb
      ansible.builtin.service:
        name: mongodb
        state: started
        enable: yes
    
    - name: allow remote conection 
      ansible.builtin.command:
        path: vim /etc/mongodb.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: restart mongodb
      ansible.builtin.service:
        name: mongodb
        state: restart