- name: redis installation
  hosts: redis
  become: yes
  tasks:
    - name: installing radis file
      ansible.builtin.command:
        cmd: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y

    - name: enable redis
      ansible.builtin.command: dnf module enable redis:remi-6.2 -y

    - name: install redis
      ansible.builtin.dnf:
        name: redis
        state: present

    - name: allow remote conection 
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: enable and start redis
      ansible.builtin.service:
        name: redis
        state: latest
        enabled: yes



